### ISSUE TITLE
"Error adding task to CAPE's database"is displayed when Submit file.

### ISSUE THREAD

**Issue by ai-suzuki** [kevoreilly/CAPEv2#290] opened 2020-10-01 01:11 UTC
## This is opensource and you getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Resolve database errors and Submit file .

# Current Behavior
_Error adding task to CAPE's database._ is displayed when Submit file.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Check if the service is running
2. Check the virtual machine is waiting for a task
3. Submit file but  error page is displayed

It worked when I built it before. Did you change the source?

## Context

Using machinery VirtualBox
Host machine: ubuntu 20.04.1 LTS
Guest machine: Windows 10 

## Failure Logs
This error page is displayed when submitting a file.

![image](https://user-images.githubusercontent.com/58881955/94754268-bd0e2f80-03cb-11eb-8208-f653d3b2bd0e.png)

The following services are running without any problems
cape-rooter
cape
cape-processor   
cape-web
postgresql

```
(venv-cape) root@cape:~# systemctl status cape
● cape.service - CAPE
     Loaded: loaded (/lib/systemd/system/cape.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-10-01 10:00:50 JST; 1min 1s ago
       Docs: https://github.com/kevoreilly/CAPEv2
   Main PID: 3785 (python)
      Tasks: 6 (limit: 19150)
     Memory: 221.6M
     CGroup: /system.slice/cape.service
             mq3785 /root/venv-cape/bin/python cuckoo.py

10月 01 10:00:51 cape python[3785]:   88   88  8 88   88   8 8   8 8   8
10月 01 10:00:51 cape python[3785]:   88e8 88ee8 88e8 88   8 8eee8 8eee8
10月 01 10:00:51 cape python[3785]:  Cuckoo Sandbox 2.1-CAPE
10月 01 10:00:51 cape python[3785]:  www.cuckoosandbox.org
10月 01 10:00:51 cape python[3785]:  Copyright (c) 2010-2015
10月 01 10:00:51 cape python[3785]:  CAPE: Config and Payload Extraction
10月 01 10:00:51 cape python[3785]:  github.com/kevoreilly/CAPEv2
10月 01 10:00:52 cape python[3785]: 2020-10-01 10:00:52,684 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" machine manager >
10月 01 10:00:53 cape python[3785]: 2020-10-01 10:00:53,050 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
10月 01 10:00:53 cape python[3785]: 2020-10-01 10:00:53,055 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
(venv-cape) root@cape:~# systemctl status cape-web
● cape-web.service - CAPE WSGI app
     Loaded: loaded (/lib/systemd/system/cape-web.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-10-01 09:29:20 JST; 32min ago
       Docs: https://github.com/kevoreilly/CAPEv2
   Main PID: 671 (python)
      Tasks: 35 (limit: 19150)
     Memory: 254.8M
     CGroup: /system.slice/cape-web.service
             tq 671 /root/venv-cape/bin/python manage.py runserver 0.0.0.0:8000
             mq1265 /root/venv-cape/bin/python manage.py runserver 0.0.0.0:8000

10月 01 10:01:18 cape python[1265]: [01/Oct/2020 01:01:18] "GET /static/js/jquery.js HTTP/1.1" 304 0
10月 01 10:01:18 cape python[1265]: [01/Oct/2020 01:01:18] "GET /static/js/bootstrap-fileupload.js HTTP/1.1" 304 0
10月 01 10:01:18 cape python[1265]: [01/Oct/2020 01:01:18] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
10月 01 10:01:18 cape python[1265]: [01/Oct/2020 01:01:18] "GET /static/js/moment.min.js HTTP/1.1" 304 0
10月 01 10:01:18 cape python[1265]: [01/Oct/2020 01:01:18] "GET /static/js/bootstrap-datetimepicker.min.js HTTP/1.1" 304 0
10月 01 10:01:18 cape python[1265]: [01/Oct/2020 01:01:18] "GET /static/js/lightbox.js HTTP/1.1" 304 0
10月 01 10:01:18 cape python[1265]: [01/Oct/2020 01:01:18] "GET /static/js/bootstrap-collapse.js HTTP/1.1" 304 0
10月 01 10:01:18 cape python[1265]: [01/Oct/2020 01:01:18] "GET /static/js/bootstrap-transition.js HTTP/1.1" 304 0
10月 01 10:01:21 cape python[1265]: [01/Oct/2020 01:01:21] "GET /submit/ HTTP/1.1" 200 42028
10月 01 10:01:28 cape python[1265]: [01/Oct/2020 01:01:28] "POST /submit/ HTTP/1.1" 200 3122
(venv-cape) root@cape:~# systemctl status cape-processor
● cape-processor.service - CAPEv2 report processor
     Loaded: loaded (/lib/systemd/system/cape-processor.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-10-01 09:29:21 JST; 32min ago
       Docs: https://github.com/kevoreilly/CAPEv2
   Main PID: 797 (python)
      Tasks: 11 (limit: 19150)
     Memory: 262.8M
     CGroup: /system.slice/cape-processor.service
             mq797 /root/venv-cape/bin/python process.py -p7 auto -pt 900

10月 01 09:29:21 cape systemd[1]: Started CAPEv2 report processor.
10月 01 09:29:31 cape python[797]: 2020-10-01 09:29:31,225 [root] INFO: Processing analysis data
(venv-cape) root@cape:~# systemctl status cape-rooter
● cape-rooter.service - CAPE rooter
     Loaded: loaded (/lib/systemd/system/cape-rooter.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-10-01 09:29:21 JST; 32min ago
       Docs: https://github.com/kevoreilly/CAPEv2
   Main PID: 795 (python)
      Tasks: 1 (limit: 19150)
     Memory: 9.7M
     CGroup: /system.slice/cape-rooter.service
             mq795 /root/venv-cape/bin/python rooter.py --iptables /usr/sbin/iptables --iptables-restore /usr/sbin/iptables-resto>

10月 01 09:29:21 cape systemd[1]: Started CAPE rooter.
(venv-cape) root@cape:~# service postgresql restart
(venv-cape) root@cape:~# ^C
(venv-cape) root@cape:~# service postgresql status
● postgresql.service - PostgreSQL RDBMS
     Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
     Active: active (exited) since Thu 2020-10-01 10:02:46 JST; 6s ago
    Process: 4127 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
   Main PID: 4127 (code=exited, status=0/SUCCESS)

10月 01 10:02:46 cape systemd[1]: Starting PostgreSQL RDBMS...
10月 01 10:02:46 cape systemd[1]: Finished PostgreSQL RDBMS.
(venv-cape) root@cape:~#
```

**Comment by doomedraven** [comment] 2020-10-01 04:14
i don't see any error, you need to dig in your servr what is wrong as capesandbox.com works just fine and it uses the same code that this repo

**Comment by a-fernandes** [comment] 2020-10-01 09:07
ok, i started to see it also, working on it

**Comment by ClaudioWayne** [comment] 2020-10-01 11:49
I can confirm this error. I did a fresh Cape installation yesterday and i also get this Error with submit.py

![grafik](https://user-images.githubusercontent.com/35531629/94804777-aed00b80-03eb-11eb-9638-3a0a347be52a.png)

Did a quick look at submit.py
The script terminates, because the list task_ids contains no items.
Maybe db.demux_sample_and_add_to_db() needs further investigations.

![grafik](https://user-images.githubusercontent.com/35531629/94805484-b9d76b80-03ec-11eb-8ed5-425cd54f8b07.png)

**Comment by doomedraven** [comment] 2020-10-01 11:57
Yes its fails on that that file not exist and it returns, but if you
specify package ir works, that is weird part, working on it

**Comment by doomedraven** [comment] 2020-10-01 12:09
But it also for some filetypes only, exe and office files works without
specify anything, i will be bacl to thos issue once it will be solved

**Comment by doomedraven** [comment] 2020-10-01 13:43
@ai-suzuki  thanks for letting me know for the issue, next time please provide a bit more details, like hash and if that is replicable on capesandbox as jsut say that something doesn't work doesn't help, update that is fixed now

**Closed by doomedraven** 2020-10-01 13:43 UTC

**Comment by ai-suzuki** [comment] 2020-10-02 00:09
@doomedraven @ClaudioWayne 
Thank you very much. I am really grateful to them.
I'm sorry, The detailed investigation was not enough and it took you a lot of trouble.
OK, I will try to give as much detail as possible!

**Comment by ai-suzuki** [comment] 2020-10-02 01:03
@doomedraven 
I try git pull and submit file(vbs file).
The error no longer appears, but  "not ready yet"


I start cape by `python cuckoo.py -d`. This is the log.
```
2020-10-02 09:40:29,843 [modules.machinery.virtualbox] DEBUG: Getting status for cape
2020-10-02 09:40:29,952 [modules.machinery.virtualbox] DEBUG: Machine cape status poweroff
2020-10-02 09:40:29,980 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2020-10-02 09:40:29,994 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2020-10-02 09:41:40,796 [lib.cuckoo.core.scheduler] DEBUG: Task #5: Processing task
2020-10-02 09:41:40,799 [lib.cuckoo.core.scheduler] INFO: Task #5: Starting analysis of FILE '/tmp/cuckoo-tmp/upload_fksajnse/time.vbs'
2020-10-02 09:41:40,809 [lib.cuckoo.core.scheduler] INFO: Task #5: File already exists at '/opt/CAPEv2/storage/binaries/c9ce04792e3fc527ddb1bdec5966bbf15a9f0dc76f8f91302267801dd7a02aef'
2020-10-02 09:41:40,824 [lib.cuckoo.core.scheduler] INFO: Task #5: acquired machine cape (label=cape, platform=windows)
2020-10-02 09:41:40,841 [root] DEBUG: Now tracking machine 192.168.56.101 for task #5
2020-10-02 09:41:40,860 [modules.machinery.virtualbox] DEBUG: Starting vm cape
2020-10-02 09:41:40,860 [modules.machinery.virtualbox] DEBUG: Getting status for cape
2020-10-02 09:41:40,964 [modules.machinery.virtualbox] DEBUG: Machine cape status poweroff
2020-10-02 09:41:40,981 [modules.machinery.virtualbox] DEBUG: Using snapshot win10 for virtual machine cape
2020-10-02 09:41:41,081 [modules.machinery.virtualbox] DEBUG: Getting status for cape
2020-10-02 09:41:41,186 [modules.machinery.virtualbox] DEBUG: Machine cape status saved
2020-10-02 09:41:50,371 [modules.machinery.virtualbox] DEBUG: Getting status for cape
2020-10-02 09:41:50,549 [modules.machinery.virtualbox] DEBUG: Machine cape status running
2020-10-02 09:41:50,603 [lib.cuckoo.core.scheduler] INFO: Enabled route 'tor'
2020-10-02 09:41:50,624 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 5192 (interface=vboxnet0, host=192.168.56.101, dump path=/opt/CAPEv2/storage/analyses/5/dump.pcap)
2020-10-02 09:41:50,625 [lib.cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2020-10-02 09:41:50,647 [lib.cuckoo.core.guest] INFO: Starting analysis #5 on guest (id=cape, ip=192.168.56.101)
2020-10-02 09:41:51,651 [lib.cuckoo.core.guest] DEBUG: cape: not ready yet
2020-10-02 09:41:52,656 [lib.cuckoo.core.guest] DEBUG: cape: not ready yet
2020-10-02 09:41:53,661 [lib.cuckoo.core.guest] DEBUG: cape: not ready yet
2020-10-02 09:41:53,664 [lib.cuckoo.core.guest] DEBUG: cape: not ready yet
2020-10-02 09:41:54,670 [lib.cuckoo.core.guest] DEBUG: cape: not ready yet
2020-10-02 09:41:55,676 [lib.cuckoo.core.guest] DEBUG: cape: not ready yet
2020-10-02 09:41:56,682 [lib.cuckoo.core.guest] DEBUG: cape: not ready yet
2020-10-02 09:41:57,688 [lib.cuckoo.core.guest] DEBUG: cape: not ready yet
2020-10-02 09:41:58,695 [lib.cuckoo.core.guest] DEBUG: cape: not ready yet
2020-10-02 09:41:59,705 [lib.cuckoo.core.guest] DEBUG: cape: not ready yet
2020-10-02 09:42:00,712 [lib.cuckoo.core.guest] DEBUG: cape: not ready yet
2020-10-02 09:42:01,718 [lib.cuckoo.core.guest] DEBUG: cape: not ready yet
```

and i look guest.py. Is this wrong?
`socket.create_connection((self.ipaddr, self.port), 1).close()`

![image](https://user-images.githubusercontent.com/58881955/94877368-42114b80-0495-11eb-9ec4-bee363218a80.png)



@ClaudioWayne 
Are you not with this error?

**Comment by doomedraven** [comment] 2020-10-02 06:02
hm we didnt touch that part, what i can suggest is to try to start or attach to remve vbox manager and see if vm starts as first step. Can you try to submit also to capesandbox.com? so we can see if we can reproduce that on our end

**Comment by ai-suzuki** [comment] 2020-10-05 01:33
I was able to analyze it with capesandbox.com.
The VM seems to be up, but it could be a problem with my server...
Thank you.

**Comment by nikhilh-20** [comment] 2020-11-24 06:06
With which commit was this issue resolved? I was trying to submit an exe (5872b7c5808419299740f3e5fef8b0c34c85a1515e68b41e244cc98a040c6e9c) to my local CAPE instance running WSGI and I hit this error. This is not reproducible on capesandbox.com and it also does not hit when I'm running Django dev server.

**Comment by doomedraven** [comment] 2020-11-24 07:23
Then that sound like permission issue, does you run it as the same user as
the rest of cape services?

**Comment by nikhilh-20** [comment] 2020-11-24 07:48
Yep, it was a permission issue. The `db` folder in CAPEv2 was under a different user than Apache user.

**Comment by doomedraven** [comment] 2020-11-24 07:49
that sound as you using sqlite3? i hope for test as i don't suggest to use it in production + cape2.2 aka see bootstrap branch(that become extended to other features) will requires db upgrade and sqlite3 isn't very friendly with that

**Comment by nikhilh-20** [comment] 2020-11-24 15:02
Yep, I do use sqlite3 and it's only for local testing.
