### ISSUE TITLE
CapeV2 tasks don't start. Debug log shows an error 

### ISSUE THREAD

**Issue by s-ribeiro** [kevoreilly/CAPEv2#1861] opened 2023-12-02 13:37 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am running the latest version
- [Y] I did read the README!
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed
- [Y] I'm reporting the issue to the correct repository (for multi-repository projects)
- [Y] I have read and checked all configs (with all optional parts)

# Expected Behavior

When I submit a new file for analysis the analysis should start.

# Current Behavior

After submission, the task  don't start. 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 22.04

I've installed cape with the cape2.sh installer script. Cuckoo Sandbox 2.4-CAPE,

## Failure Logs

 
./log/cuckoo.log:2023-12-02 13:25:09,121 [lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list. 
./log/cuckoo.log:2023-12-02 13:25:09,123 [lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list. 

I could not find this issue in past issues or documentation, so I kindly request any guidance to solve it.

Thanks in advance

**Comment by s-ribeiro** [comment] 2023-12-02 14:11
Thanks.
When running the UI manually noticed that some db migrations were pending.

"sudo -u cape poetry run /usr/bin/python3 -m poetry run python manage.py migrate"

Ran this command. Restarted the cape instance and now it is working fine.

**Comment by s-ribeiro** [comment] 2023-12-02 14:15
downloaded cape2.sh 
and then executed "./cape2.sh all cape | tee cape.log"

**Comment by doomedraven** [comment] 2023-12-04 07:58
that msg is more warning than error, how did you run cape? i need more details to try to get some basic idea about your setup first

**Comment by Buts94** [comment] 2023-12-12 15:19
Same error described by @s-ribeiro. Installed CAPE with cape2.sh and executed with : "./cape2.sh all cape | tee cape.log". 
All seems work fine the cape.service service load kvm machines correctly and the web interface is up. But tasks are stuck in pending and if launch : sudo -u cape poetry run python3 cuckoo.py -d. The following error is continually triggered:

`./log/cuckoo.log:2023-12-02 13:25:09,123 [lib.cuckoo.core.database] DEBUG: Database error counting tasks: The "entities" argument to Select.with_only_columns(), when referring to a sequence of items, is now passed as a series of positional elements, rather than as a list.
`

I launched the command suggested : 

`sudo -u cape poetry run /usr/bin/python3 -m poetry run python manage.py migrate`

some migrations have been performed but the tasks are the same stucked in pending. Can anyone help me ?

Same @s-ribeiro setup : Ubuntu 22.04 Desktop.

**Comment by Buts94** [comment] 2023-12-13 08:56
Found the code bug. I had to restore the old code for function `count_tasks` in /lib/cuckoo/core/database because the commit https://github.com/kevoreilly/CAPEv2/commit/224714645fcf4f6f45900c5d445f143fb8f467a4.

The new function get_count trigger an exception which leads to an infinite loop not fetching the pending tasks because return always 0.

**Comment by doomedraven** [comment] 2023-12-13 10:15
nice finding, i can't test that(phone only), but that become interesting how that affect only some and not all. what is your `sqlalchemy` version? you can get it with `poetry run pip freeze|grep SQLAlchemy`

```
SQLAlchemy = "1.4.22"
SQLAlchemy-Utils = "0.37.8"
```

**Comment by Buts94** [comment] 2023-12-13 10:35
Just runned the poetry dependencies list, installed same version  :

`SQLAlchemy = "1.4.22"
SQLAlchemy-Utils = "0.37.8"`

**Comment by doomedraven** [comment] 2023-12-13 20:18
btw provide info about your setup, i don't see anything related to your database

**Comment by doomedraven** [comment] 2023-12-13 21:21
>> The new function get_count trigger an exception which leads to an infinite loop not fetching the pending tasks because return always 0.

i would love to see the traceback as i can't reproduce it, my db is:`postgresql  16+256.pgdg22.04+1` you def should have some library or db different than most of us as i can't trigger that in any way with current code. So i will need all the details about your setup + that traceback error

**Comment by doomedraven** [comment] 2023-12-13 21:23
+ im not sure how it can impact that tasks doesn't start as that only used for webgui

```
./web/analysis/views.py:    tasks_files_number = db.count_matching_tasks(category="file", not_status=TASK_PENDING) or 0
./web/analysis/views.py:    tasks_static_number = db.count_matching_tasks(category="static", not_status=TASK_PENDING) or 0
./web/analysis/views.py:    tasks_urls_number = db.count_matching_tasks(category="url", not_status=TASK_PENDING) or 0
./web/analysis/views.py:    tasks_pcaps_number = db.count_matching_tasks(category="pcap", not_status=TASK_PENDING) or 0
./lib/cuckoo/core/database.py:    def count_matching_tasks(self, category=None, status=None, not_status=None):
```

**Comment by doomedraven** [comment] 2023-12-13 21:29
btw this should be a fix

```
-    count_q = q.statement.with_only_columns([func.count()]).order_by(None)
+   count_q = q.statement.with_only_columns(func.count()).order_by(None)
```

if you can test that would be great

**Comment by doomedraven** [comment] 2023-12-13 22:04
this should fix it https://github.com/kevoreilly/CAPEv2/pull/1888

**Comment by doomedraven** [comment] 2023-12-14 06:25
btw as another user suggested you can try
poetry run pip install --force-reinstall Flask-SQLAlchemy==3.0.5
poetry run pip install --force-reinstall SQLAlchemy==1.4.50

**Comment by Buts94** [comment] 2023-12-14 08:15
I try to test as soon as possible.

**Comment by Buts94** [comment] 2023-12-14 13:58
Confirm all working fine.

**Comment by doomedraven** [comment] 2023-12-14 15:17
which of them? PR or dependency reinstaall?

**Comment by Buts94** [comment] 2023-12-14 15:40
No, I've only tested the branch https://github.com/kevoreilly/CAPEv2/pull/1888. All working with same dependencies.

**Comment by doomedraven** [comment] 2023-12-14 15:58
great, thank you for feedback, closing this as solved, Merging that PR

**Closed by doomedraven** 2023-12-14 15:58 UTC
