### ISSUE TITLE
session.add(machine) in database.py unlock_machine function causes analysis to fail.

### ISSUE THREAD

**Issue by Cassandra-Fu** [kevoreilly/CAPEv2#2225] opened 2024-07-14 11:39 UTC
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes] I am running the latest version
- [yes] I did read the README!
- [yes] I checked the documentation and found no answer
- [yes] I checked to make sure that this issue has not already been filed
- [yes] I'm reporting the issue to the correct repository (for multi-repository projects)
- [yes] I have read and checked all configs (with all optional parts)

# Expected Behavior

Analysis is supposed to be completed.

# Current Behavior

Analysis fails and then became inaccurate.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Pulled current repo
2. submit sample analysis
3. Analysis status is completed but the analysis report is not returned as the task is not released from machine. 

## Context
I tried to setup on a Ubuntu 22.04 machine and it worked but the when i tried to submit a sample for analysis, I received an error below which came from the unlock machine function. Apparently the session.add line is causing a race condition. As a result the analysis fails when the status is complete.:
![image](https://github.com/user-attachments/assets/121e1ecd-a30e-4de1-9417-ab1cd767c3cd)

Once way I tried to fix the issue was by commenting out the session.add line in lock_machine and it worked but I had to restart my cape server  everytime I start another analysis because the analysis machine was still locked to the previous task.
![image](https://github.com/user-attachments/assets/ba971dab-1914-40db-8f90-cb24eeced7ec)

I then reset up a cleaned version of cape but cloned from the flare_capa_7 branch so the error is fixed because of it was using the working version of the database.py file. But then the results for a bumblebee sample i used for testing the setup changed from this:
![image](https://github.com/user-attachments/assets/fbc0dc3f-285c-42a3-a768-2282a099a7bf)

to this (on the new setup):
![image](https://github.com/user-attachments/assets/defcc4c9-0f5a-4bfb-b7a0-7f6bdb92221f)

Is it possible to revert the database.py to before session.add was used to unlock the machine ? 

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log \| head -n1` to find out
| OS version       | Ubuntu 22.04, win10 21H2 (for analysis machine)

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by Cassandra-Fu** [comment] 2024-07-14 11:43
Here is a clearer picture of the original error 
![image](https://github.com/user-attachments/assets/59a478d3-a098-4b77-9727-4dd779bb2cb3)

**Comment by doomedraven** [comment] 2024-07-14 12:29
Hey what version of sqlachemy do you have?

**Comment by Cassandra-Fu** [comment] 2024-07-15 00:58
sqlalchemy version 1.4.50
![image](https://github.com/user-attachments/assets/ff45752a-7088-4f52-961f-4151602cc7b7)

**Comment by doomedraven** [comment] 2024-07-15 06:01
@tbeadle just for thing, do we miss `with self.session.begin_nested():` here https://github.com/kevoreilly/CAPEv2/edit/master/lib/cuckoo/core/database.py#971? i don't think so, but just in case to sync

**Comment by tbeadle** [comment] 2024-07-15 14:00
@Cassandra-Fu could you please enable the "log_statements" config item in the [database] section of cuckoo.conf, restart the cape-scheduler, and re-run the analysis? Then, attach the resulting logs from cape-scheduler.

**Comment by Cassandra-Fu** [comment] 2024-07-16 15:04
![image](https://github.com/user-attachments/assets/fae55edf-2698-484c-8222-448466ae47fb)

These are the logs I received on my end.

**Comment by tbeadle** [comment] 2024-07-16 17:34
That is only the query for getting a pending task. I'm going to need much more than that. In particular, I'll need to see from this point up until you get the error.

**Comment by Cassandra-Fu** [comment] 2024-07-20 01:52
I managed to resolve the problem by reverting to commit e89be36522a21b184b69fb446ecd2ceb211f5a79.

**Comment by ChrisThibodeaux** [comment] 2024-07-20 01:59
Thank you for the update. I've been trying to trace down odd sqalchemy issues for three days. I will give that commit a shot!

**Comment by doomedraven** [comment] 2024-07-23 09:50
well i can't reproduce it and as the author of the issue didn't provide info to try to fix it and just reverted to some "random" commit, closing it

**Closed by doomedraven** 2024-07-23 09:50 UTC
