### ISSUE TITLE
Status of analysis is Running for a long time, so I checked the process.py file and it is giving error: "Failed to get start/end time from Task"

### ISSUE THREAD

**Issue by dhruvpatel56** [kevoreilly/CAPEv2#1029] opened 2022-07-28 19:29 UTC
## Removing issue template is equivalent to invalid issue!
* We have this template in order to not have to ask everyone the same questions again and again!
- [ ] I understand that if I remove this template this issue will be automatically closed without answer

## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account acctivation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes] I am running the latest version
- [yes ] I did read the README!
- [yes ] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed
- [yes ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [yes ] I'm have read all configs with all optional parts
- [yes ] I'm have checked [discussions section](https://github.com/kevoreilly/CAPEv2/discussions)

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__
Status should not be in "Running" mode for a long period of time. Basically, it should be completed after a while.

# Current Behavior

What is the current behavior?
The status is in Running mode for a long period of time.
![image](https://user-images.githubusercontent.com/50963903/181621302-66a93ad5-3a60-4a1e-8b9c-88446fa8b383.png)

So, I checked the process.py using "python3 utils/process.py 6" and it is giving below error:
![image](https://user-images.githubusercontent.com/50963903/181621504-a0e83b5a-4b6f-459b-ab81-d6fab025dccf.png)

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

**Comment by doomedraven** [comment] 2022-07-28 20:23
can you share hash or submit to capesandbox?

**Comment by dhruvpatel56** [comment] 2022-07-28 21:16
Here's the SHA256 Hash:
1e9d66214e14db47f910fa05eeebb9331dbfcccc0672829a3f007571c3acf309

**Comment by doomedraven** [comment] 2022-07-28 21:35
works fine on our side https://capesandbox.com/analysis/294980/ should be something on your side. That error is not in that module, so no idea what is wrong on your side, you will need to dig on your own here

**Comment by dhruvpatel56** [comment] 2022-07-28 23:06
As soon as I submit the sample for analysis, the Guest VM shuts down. Can you please tell what could be an issue or what configs need to be changed?
Thanks!

**Comment by doomedraven** [comment] 2022-07-29 05:39
Uff no idea, you need to debug that you Def has somethimg wrong, check wiki
in this project how to debug this case, part of CAPE_DBG=1

**Comment by doomedraven** [comment] 2022-07-29 06:20
https://github.com/kevoreilly/CAPEv2/wiki/Tips'n'Tricks#how-to-debug-analyzer-and-any-script-that-executes-inside-of-the-virtual-machine

**Comment by doomedraven** [comment] 2022-07-29 06:20
as we can't reproduce this issue im closing it. but feel free to ask here or post what was wrong

**Closed by doomedraven** 2022-07-29 06:20 UTC

**Comment by dhruvpatel56** [comment] 2022-07-29 17:03
Thanks for your help! I will give it a shot.
