### ISSUE TITLE
RtlDispatchException when CAPE agent starts the sample EXE

### ISSUE THREAD

**Issue by nikhilh-20** [kevoreilly/CAPEv2#435] opened 2021-02-09 02:57 UTC
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I'm have read all configs with all optional parts

# Expected Behavior

A successful execution of the sample.

# Current Behavior

CAPE's agent starts the sample which crashes and `agent.py` logs mention a `RtlDispatchException`. The sample itself is functional and runs correctly if I start it from the cmdline. CAPE's agent also works correctly on another Win10 x64 sandbox that I've setup. So, I'm not sure what's going wrong with Win10 x86.

My question: which part of CAPE's code is the error occurring in? I've tried searching for the log strings that are shown before the `RtlDispatchException` but I've not been able to find them in CAPEv2's repo.

# Steps to Reproduce

N/A

# Context

| Question         | Answer
|------------------|--------------------
| Git commit      | fabeda3dffe6b6b5d5d3e433d9601f0563b29acd
| OS version      | Ubuntu 20.04
| Sandbox OS | Win10 x86
| Python | Python 3.8 x86

# `agent.py` Failure logs

Log1

![RtlDispatchException_agent](https://user-images.githubusercontent.com/9674215/107309182-f3ce1380-6a57-11eb-9c9b-45bd25a53a89.png)

Log2

![RtlDispatchException_agent2](https://user-images.githubusercontent.com/9674215/107310720-fa11bf00-6a5a-11eb-8890-192347261ac3.png)

**Comment by kevoreilly** [comment] 2021-02-09 06:24
I'm thinking the most important piece of information by far is missing here... what sample?!

**Comment by kevoreilly** [comment] 2021-02-09 06:39
To answer your question generally - the component you are looking for is the monitor and it has a whole separate repo as it's a whole other world... https://github.com/kevoreilly/capemon

**Comment by nikhilh-20** [comment] 2021-02-09 14:07
> I'm thinking the most important piece of information by far is missing here... what sample?!

This is it: d67c059b09f21327cbfe888a11f869c6b3c7190f2d7e1d5c18d5ca219545be99

> To answer your question generally - the component you are looking for is the monitor and it has a whole separate repo as it's a whole other world... https://github.com/kevoreilly/capemon

Do the logs tell you anything about what the problem could be? In the meantime, I'll be looking in capemon and see if I can pinpoint a location.

**Comment by kevoreilly** [comment] 2021-02-09 14:10
It is by having the sample that I will be able to debug this problem! So thanks for the hash. Let me get back to you.

**Comment by kevoreilly** [comment] 2021-02-09 14:17
Ah it's an old Emotet sample. Can you try running with the following options:

caller-dump=0,yarascan=0

Let me know if that makes any difference.

**Comment by nikhilh-20** [comment] 2021-02-09 14:30
I see those options are read in `config.c` in capemon but where do I set them in CAPEv2?

**Comment by kevoreilly** [comment] 2021-02-09 14:40
paste into options

**Comment by kevoreilly** [comment] 2021-02-09 14:41
![image](https://user-images.githubusercontent.com/22219888/107379453-d98e4700-6ae4-11eb-8a93-4e2862fa930d.png)

**Comment by nikhilh-20** [comment] 2021-02-09 14:42
Ah okay :) I'll check and get back to you. Thanks!

**Comment by nikhilh-20** [comment] 2021-02-09 18:36
That doesn't seem to have worked:

![RtlDispatchException_agent3](https://user-images.githubusercontent.com/9674215/107410885-dcd10500-6adb-11eb-9769-4c572c65d4ee.png)

**Comment by nikhilh-20** [comment] 2021-02-09 18:43
The issue is the same for a WannaCry sample (df6d5b29a97647bca44e2306069f7675ef992f591c8c761af99bbdc17cfa7692) as well

![RtlDispatchException_agent4](https://user-images.githubusercontent.com/9674215/107411648-caa39680-6adc-11eb-81d0-3ee059fc6792.png)

**Comment by nikhilh-20** [comment] 2021-02-09 22:07
The Emotet sample doesn't crash when I provide `free=1` option but then that's no monitoring, so the report isn't especially helpful.

**Comment by nikhilh-20** [comment] 2021-02-10 16:44
I think this log might give you more information. I ran the Emotet sample (d67c059b09f21327cbfe888a11f869c6b3c7190f2d7e1d5c18d5ca219545be99) with options - `caller-dump=0,yarascan=0,debug=1`. The previous RtlDispatchException was caught.

![RtlDispatchException_agent5](https://user-images.githubusercontent.com/9674215/107541551-3ea17580-6b95-11eb-840d-a383617ca396.png)

**Comment by kevoreilly** [comment] 2021-02-12 14:51
The exception is not from within capemon, and it's working fine on Win7, so I would infer it's an incompatibility due to changes in Windows. The problem is I don't have a 32-bit Win10 to test on, I have only built a 64-bit vm so far... well at least until this morning. Let me finish off preparing this 32-bit Win10 vm then I can just debug it myself which will be much more efficient. It's something I need to do anyway so this is a good reason to get going.

**Comment by nikhilh-20** [comment] 2021-02-18 14:35
Did you have any luck figuring out the problem, @kevoreilly ?

**Comment by matrixpdb** [comment] 2021-03-01 14:36
Take a test.
Even with python 3.6.8 installed, install python2.7 on the host
I had this problem and after I got the two versions of python installed on windows the errors stopped.

**Comment by nikhilh-20** [comment] 2021-03-01 16:01
That didn't work. I had Python 3.8.0 x86 installed. So, I install Python 2.7 x86 on the host and ran `agent.py` with Python 3.8.0. Same error. I tried running `agent.py` with Python 3.6.8 x86 (with Python 2.7 x86 also installed on the sandbox) but got the same error.

**Comment by doomedraven** [comment] 2021-04-21 18:51
is this solved?

**Comment by doomedraven** [comment] 2021-04-23 12:52
closing, reopen if needed

**Closed by doomedraven** 2021-04-23 12:52 UTC

**Comment by nikhilh-20** [comment] 2021-04-23 22:40
This wasn't solved. I just moved on to using x64 Windows

**Comment by doomedraven** [comment] 2021-04-24 05:27
@kevoreilly was you able to reproduce this on w10x86?

**Comment by kevoreilly** [comment] 2021-04-24 08:01
Afraid not - I haven't had time unfortunately. There are a million other issues that I've been maxed out working on even in Win7. I have done some work on x64 compatibility since I have this set up but my x86 vm still isn't finished, it's just waiting under a massive pile of other more pressing issues I'm afraid to say.

To be fair if we are gonna have an issue here, let's just be honest and call it 'Win 10 compatibilty is not 100%' or similar because in truth the list of issues on Win10 is long. doomed you know I have been working on getting a batch file to launch calc working in on Win10x64. This particular issue is a drop in the ocean.
