### ISSUE TITLE
Quarantined file does not get Decrypted

### ISSUE THREAD

**Issue by JTurn01** [kevoreilly/CAPEv2#2166] opened 2024-06-10 18:58 UTC
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X ] I am running the latest version
- [ X ] I did read the README!
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed
- [ X ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ X ] I have read and checked all configs (with all optional parts)

# Expected Behavior

Please describe the behavior you are expecting. __If your samples(x64) stuck in pending ensure that you set tags=x64 in hypervisor conf for x64 vms__

When I submit a quarantined file, it should decrypt the file and analyze the decrypted file. 

# Current Behavior

When I submit a quarantined file, it does not get decrypted, and the encrypted file gets analyzed instead. 

# Failure Information (for bugs)

According to this CAPE commit, there was a change which should detect that the file is quarantined from a normal file submit and try to decrypt it. 
https://github.com/kevoreilly/CAPEv2/pull/1399

Here is the file I am trying to submit
![image](https://github.com/kevoreilly/CAPEv2/assets/23060454/94a0151f-59ff-43ff-a350-475f41ff5f1b)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Operating system version, bitness, installed software versions, test sample details/hash/binary (if applicable).

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 22.04

## Failure Logs

Analysis Log:
https://pastebin.com/Kef7Kser

**Comment by doomedraven** [comment] 2024-06-10 19:50
Attach file here, without that is dead end

**Comment by JTurn01** [comment] 2024-06-10 20:16
Github won't let me attach it but you can find it here:
https://file.io/XGmiZoaDqwmW

It is an EICAR test file

**Comment by doomedraven** [comment] 2024-06-11 06:58
it works just fine here, you must be doing something wrong

![Screenshot from 2024-06-11 08-57-39](https://github.com/kevoreilly/CAPEv2/assets/1856495/1c095d54-7c8d-412f-90fe-34c3c60f7234)

**Comment by JTurn01** [comment] 2024-06-11 13:00
I'm glad it's working somewhere! I am uploading the file via the WebGUI and setting the Analysis Package to detect automatically. Here is the result of the analaysis:
![image](https://github.com/kevoreilly/CAPEv2/assets/23060454/36325f3d-5e2b-4848-b332-db6b41f740e9)

Any idea where I should look to start debugging?

**Comment by doomedraven** [comment] 2024-06-11 13:55
is the same that i do, but i dont touch packages as is already set to auto, but there is no much what you can dig into, https://github.com/search?q=repo%3Akevoreilly%2FCAPEv2+Quarantine&type=code see there is automaticall check for that, maybe you have some dependency problem if you didnt use cape2.sh to install it, you can view it here https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/common/quarantine.py

**Comment by MReprogle1** [comment] 2024-06-12 00:15
I am actually running into this very same issue. I send quarantined files over a they just come in as 'general' files, so it seems that CAPE doesn't attempt to realize that it is a quarantined file. 

@doomedraven when you say to put a breakpoint on quarantine, do you mean to use pdb and import it in at the beginning of that quarantine file to debug it? Sorry, I am not super familiar with python, but am trying to get this last piece working.

**Comment by doomedraven** [comment] 2024-06-12 06:27
yes any tool that allow you debug python, also bear in mind if you testing some file that was quarantined by tool X it wont be handled, so you need to ensure that it works, as attached file from original issue, that one works just fine.

i just added posibility to call that file directly so you dont need to debug it, but you need to run it from `/opt/CAPEv2` something like(inside of the poetry shell): 
`PYTHON_PATH=$PWD python lib/cuckoo/common/quarantine.py <path to sample to test>`

**Comment by JTurn01** [comment] 2024-06-12 13:56
Ran command provided to test file, got this:

cybersecurity@FWM-CYBERSECURITY-CAPE1:/opt/CAPEv2$` PYTHONPATH=$PWD python3 lib/cuckoo/common/quarantine.py /home/cybersecurity/Downloads/213D8090764C8F777E5C373B1C5CB1E8D7B4C85A
DEBUG:__main__:Trying unquarantine function mse_unquarantine for file /home/cybersecurity/Downloads/213D8090764C8F777E5C373B1C5CB1E8D7B4C85A
DEBUG:__main__:Starting MSE unquarantine for file /home/cybersecurity/Downloads/213D8090764C8F777E5C373B1C5CB1E8D7B4C85A
DEBUG:__main__:Trying unquarantine function kav_unquarantine for file /home/cybersecurity/Downloads/213D8090764C8F777E5C373B1C5CB1E8D7B4C85A
DEBUG:__main__:Starting KAV unquarantine for file /home/cybersecurity/Downloads/213D8090764C8F777E5C373B1C5CB1E8D7B4C85A
DEBUG:__main__:Trying unquarantine function trend_unquarantine for file /home/cybersecurity/Downloads/213D8090764C8F777E5C373B1C5CB1E8D7B4C85A
DEBUG:__main__:Trying unquarantine function sep_unquarantine for file /home/cybersecurity/Downloads/213D8090764C8F777E5C373B1C5CB1E8D7B4C85A
DEBUG:__main__:Starting SEP unquarantine for file /home/cybersecurity/Downloads/213D8090764C8F777E5C373B1C5CB1E8D7B4C85A
DEBUG:__main__:Unsupported data offset: 2550181131
Unsuported quarantine file format

Odd how it works on your end. and not mine, with the same file too.
Any advice based on the log?

**Comment by doomedraven** [comment] 2024-06-12 14:59
i have no clue how it doest work on your side. I just added a bit more info to show hashes

```
/opt/CAPEv2$ PYTHONPATH=$PWD python3 lib/cuckoo/common/quarantine.py 213D8090764C8F777E5C373B1C5CB1E8D7B4C85A
Suported quarantine file format: 
 Original: de0b2f4fd6c8bae261a3bc5ae02d2936fcce23c3fcd834f790f3768511560910 - unqarantined: 275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f

```

**Comment by doomedraven** [comment] 2024-06-12 15:02
is those debug lines of logging added for you or you using some fork ?

**Comment by doomedraven** [comment] 2024-06-12 15:04
func that unquarantine it is `mse_unquarantine`

**Comment by doomedraven** [comment] 2024-06-12 15:06
so my main guess is that you guys has some problems with ARC4 library

just tested on those 2 libraries, so verify your version and upgrade if required
```
pycryptodomex==3.19.1
pycryptodomex==3.20.0

```

**Comment by JTurn01** [comment] 2024-06-12 15:37
> is those debug lines of logging added for you or you using some fork ?

Only for me, set logging to debug in quarantine.py using `logging.basicConfig(level=logging.DEBUG)`

**Comment by doomedraven** [comment] 2024-06-12 15:57
Well the code works fine so I have no clue what is wrong on your side sadly

**Comment by JTurn01** [comment] 2024-06-12 18:36
It almost works, running your command does decrypt the file:
![image](https://github.com/kevoreilly/CAPEv2/assets/23060454/19f780f2-9599-44b6-a3cb-8263a1cf0e7e)
![image](https://github.com/kevoreilly/CAPEv2/assets/23060454/7d3f84ae-5817-4802-9b95-37ce11433e51)

File submit by Web UI is not decrypted

Only difference noticed is the owner of file in /tmp/cuckoo-tmp/

Decrypted file:
![image](https://github.com/kevoreilly/CAPEv2/assets/23060454/4074a185-571c-4d20-bd5c-6b50a3212e0d)

Encrypted file submitted from Web UI:
![image](https://github.com/kevoreilly/CAPEv2/assets/23060454/db186064-e2e7-4991-bc54-89a72d64bc69)

**Comment by doomedraven** [comment] 2024-06-12 18:57
oh dead, do you run web as root?

**Comment by JTurn01** [comment] 2024-06-12 19:14
Here is way I start CAPE
![image](https://github.com/kevoreilly/CAPEv2/assets/23060454/760f34a0-52d7-4b04-956b-1d9f2d68584a)

Does that answer?

If not, how do I check what user is running web?

**Comment by doomedraven** [comment] 2024-06-12 19:17
that is totally not related to the web, did you read the readme? `systemctl status cape-web` but as you said, your file is under root after submission, so cape can't access files owner by root

**Comment by JTurn01** [comment] 2024-06-12 19:23
Sorry for mixup, file gets decrypted by using command 
PYTHONPATH=$PWD python3 lib/cuckoo/common/quarantine.py /home/cybersecurity/Downloads/213D8090764C8F777E5C373B1C5CB1E8D7B4C85A 
and the decrypted file owner is root

When submitting by web, it does not get decrypted and the file owner is cape

Here is `systemctl status cape-web`:
![image](https://github.com/kevoreilly/CAPEv2/assets/23060454/4d1419c8-38cf-4894-8a80-d4c3bb8cf3ed)

**Comment by doomedraven** [comment] 2024-06-12 19:27
that because you run it incorrectly, NEVER EVER use `sudo` with cape, you will break permissions on many things, ALWAYS `cape` user only. 

how did you install cape? i see some stuff in this log that shouldn't fail and i have feeling that you didnt follow docs or used official scripts

**Comment by JTurn01** [comment] 2024-06-12 19:49
What is the thing I run incorrectly? 

If you would like to read the steps I followed here:
https://github.com/JTurn01/capev2install/blob/main/README.md
Everything from there follows docs and official scripts with few additions. Everything was installed using cape2.sh including the web service

My cape-web.service looks like this:
![image](https://github.com/kevoreilly/CAPEv2/assets/23060454/37b2016c-623b-45b7-aeb2-81ad48df26a9)

**Comment by doomedraven** [comment] 2024-06-12 20:04
first image in this post https://github.com/kevoreilly/CAPEv2/issues/2166#issuecomment-2163675411

so i did check in diagonal, server side instalation looks ok, but don't use my private repo, you have to use scripts only from cape2 for kvm-qemu.sh, i don't support public version of my repo

i also see that you have some weird errors like yara, sflock, removing 2 lines of code is not fix, it means that install didn't work well, so you need to read the log that was generated by `| tee X`

another note, `running cape section` is not correct, well yes but no, cape and other services are executed by default, so you have just to restart cape services after edit configs

well as we can't reproduce this error, i spend a lot of time here, i tested that sample on many different cape servers that i have and it worked on all, so i would suggest go back and read log files generated on installation, closing this as not reproducible

**Closed by doomedraven** 2024-06-12 20:04 UTC

**Comment by JTurn01** [comment] 2024-06-12 20:13
Thank you for helping, at this point I am going to try reinstalling cape on a new VM and just seeing what happens, making sure to detail everything. 

Once again, thank you.

**Comment by doomedraven** [comment] 2024-06-12 20:16
pay a lot of attention to log, and store them as gold for future checks when something going wrong, is pure gold for debugging issues

**Comment by kevoreilly** [comment] 2024-06-13 07:53
``reinstalling cape on a new VM``

This does not sound like a recommended setup. If cape is running in a vm then I hope you are running remote machinery e.g. ``kvm-remote`` rather than running nested Windows vms.

**Comment by JTurn01** [comment] 2024-06-18 15:28
Want to give a little update, the problem is not occurring anymore upon the fresh install of CAPE. 
I am not sure what was wrong, but I know to make sure everything is run with CAPE user now.
