### ISSUE TITLE
VirusTotal (VT) section not filling in on Web GUI

### ISSUE THREAD

**Issue by JTurn01** [kevoreilly/CAPEv2#2239] opened 2024-07-17 15:23 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X ] I am running the latest version
- [ X } I did read the README!
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed
- [ X ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ X ] I have read and checked all configs (with all optional parts)

# Expected Behavior

Web GUI shows VT results and detections.

# Current Behavior

Web GUI does not show VT results or detections when viewing a file.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Submit the file for analysis
2. Wait for report to come back and check 'recent' from Web GUI or click on the specific file and look at the report

## Context

I have all VirusTotal configurations seemingly set correctly within processing.conf. If there is another configuration that needs to be set before VT can be put into the WebGUI, please let me know, otherwise I think it may be an issue. (Files were already analyzed in VirusTotal, so it is not an issue of it being a file that VT has not seen before)

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 22.04

## Failure Logs

![image](https://github.com/user-attachments/assets/9eb24eaf-897d-4d9f-9aee-afb23b8affd4)
![image](https://github.com/user-attachments/assets/4d4747b7-b78e-4ece-a06e-6cbbeaadd932)
![image](https://github.com/user-attachments/assets/e9f2156e-2deb-4b9d-aa24-641fba536e8a)

**Comment by doomedraven** [comment] 2024-07-22 07:53
to make it work you need your own apikey, as that key is used around all cuckoo, cuckoo-modified and cape instances. 
```
b'{\n    "error": {\n        "code": "QuotaExceededError",\n        "message": "Quota exceeded"\n    }\n}'
```

**Comment by MikeEffect** [comment] 2024-07-22 11:31
I have the same problem, but with **URL analysis** :( 
**I use the API key from my VT account**. The VT results in the case of **file analysis** are displayed in "Recent". 
Also, the key usage statistics on VT show API requests by files, **but not by URL**. 
In _"processing.conf"_ in the **[detections]** section: _virustotal = yes_, in the **[virustotal]** section: _do_url_lookup = yes_ parameter, the API key was entered correctly.

![image](https://github.com/user-attachments/assets/83242efe-6b75-4cd5-905d-172c0fc7bfe2)
![image](https://github.com/user-attachments/assets/83c15922-bce2-405d-9846-65bfe2e625c2)
![image](https://github.com/user-attachments/assets/08790f8f-18ba-46dd-8e5e-e5613b863546)
![image](https://github.com/user-attachments/assets/4ee1d95d-64a7-42b6-9fef-1bfd587e9142)

**analysis.log of the last URL analysis:**
[analysis.log](https://github.com/user-attachments/files/16332179/analysis.log)

Please help me understand what the problem is.

**Comment by doomedraven** [comment] 2024-07-22 11:51
remove screen with your apikey, yes url analysis is not supported yet, i have added code, but requires testing, will try to test it this week if will find some code, the file lookup itself works fine, have just verified with private apikey

**Comment by MikeEffect** [comment] 2024-07-22 11:52
> remove screen with your apikey, yes url analysis is not supported yet, i have added code, but requires testing, will try to test it this week if will find some code, the file lookup itself works fine, have just verified with private apikey

Understood, thank you very much

**Comment by doomedraven** [comment] 2024-07-22 14:28
thanks fixed the path, this part itself is broken, it needs to check everything as it something that i never used, but this week i don't have spare time to go and properly make it working

**Comment by doomedraven** [comment] 2024-07-22 17:14
![image](https://github.com/user-attachments/assets/42a591c2-ce3d-4fa7-8d02-66adb8e2964b)
so i have pushed files info fix. the URL requires url lookup api update

**Comment by doomedraven** [comment] 2024-07-22 19:27
url works now too, git pull and reprocess any job to see it

**Comment by MikeEffect** [comment] 2024-07-23 06:28
> url works now too, git pull and reprocess any job to see it

Cool, it works. Thank you so much :)

**Comment by doomedraven** [comment] 2024-07-23 06:30
glad to hear that, @JTurn01 does it works for you? if yes close the issue plz

**Closed** 2024-07-24 12:53 UTC
