### ISSUE TITLE
 No screenshots and no results in the Summary tabs

### ISSUE THREAD

**Issue by g9990** [kevoreilly/CAPEv2#445] opened 2021-02-14 13:46 UTC
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes] I am running the latest version
- [yes] I checked the documentation and found no answer
- [yes] I checked to make sure that this issue has not already been filed
- [yes] I'm reporting the issue to the correct repository (for multi-repository projects)
- [yes] I'm have read all configs with all optional parts

# Issue 

I am facing an issue regarding screenshots and no results in the Summary tabs, I have attached the the screenshot of the issue.

I have followed the CAPE's v2 documentation and still having the same problem.1

![cape-2021-02-14-03-42-57](https://user-images.githubusercontent.com/79043891/107878465-cefbf500-6eca-11eb-82b3-fccdab26cce4.png)

# Expected Behavior

To be able to get screenshot and summary details.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce
N/A

## Context

N/A

| Question         | Answer
|------------------|--------------------
| OS version       | Linux ubuntu 20.04.1

## Failure Logs
![cape-log1](https://user-images.githubusercontent.com/79043891/107878359-0027f580-6eca-11eb-97bc-2a94b9db2103.PNG)
![cape-log2](https://user-images.githubusercontent.com/79043891/107878360-01592280-6eca-11eb-8351-caf0db2731e6.PNG)

**Comment by kevoreilly** [comment] 2021-02-14 14:51
Great thanks. By behavior log I should have been more descriptive - I meant the behavior tab in the web interface. But I can tell it will be empty as it looks like the vm is not even talking to the server. 

I would revisit the agent installation in the vm. Is the correct IP address in the vm config? Can you reach the server from inside the vm? Check all things agent.

**Comment by g9990** [comment] 2021-02-17 06:14
agent ip 192.168.56.104
server ip 192.168.56.1
![canReach](https://user-images.githubusercontent.com/79043891/108163754-6c337500-70e7-11eb-99e2-9a7438c94355.PNG)


appearently, i can reach the server from the vm (agent)!!

**Comment by ClaudioWayne** [comment] 2021-02-17 10:59
Hello maybe you could provide more information so the community can help you. 

Can you provide [machinery].conf (kvm.conf / virtualbox.conf etc), cuckoo.conf
How did you start your agent inside snapshot, is agent.py running?
Did you disable Windows Sercurity stuff (Firewall, Defender etc)?

**Comment by g9990** [comment] 2021-02-17 11:19
here is the config files 
[configFiles.zip](https://github.com/kevoreilly/CAPEv2/files/5995170/configFiles.zip)


about the agent, yes it start automatically and i put it in startup folder.Also windows defender and firewall proper settings are made.

![agentConfig](https://user-images.githubusercontent.com/79043891/108197183-f0025700-7111-11eb-859a-586465c44707.PNG)
![defender](https://user-images.githubusercontent.com/79043891/108197186-f1338400-7111-11eb-87d7-662f78caa62f.PNG)
![firewall](https://user-images.githubusercontent.com/79043891/108197191-f1cc1a80-7111-11eb-85fa-5a7c9265f17d.PNG)

**Comment by ClaudioWayne** [comment] 2021-02-17 11:45
Not sure about this startup tap in taskmanager in windows 10. It doesnt exist in win7.
What you can try:
Put your agent in C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup
Restart your windows vm
DoubleCheck if windows security is still disabled
Check if pythonw.exe pyw.exe exists in processlist or if you dont use .pyw check if cmd window appears.
Take Snapshot
Change Snapshotname in virtualbox.conf
Restart cape services
Try analysis again

For configs:
seems fine but i dont use the optional resultserver ip and port in virtualbox.conf
pay attention to: NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.

**Comment by doomedraven** [comment] 2021-02-18 20:27
ping isn't agent communication
* restore snapshot by hand then `curl vm_ip:8000` and post output

**Comment by g9990** [comment] 2021-02-21 08:01
>     * curl vm_ip:8000
![curl-vm](https://user-images.githubusercontent.com/79043891/108619186-ee3ed900-741a-11eb-8f7e-8ca8ca3b818d.PNG)

**Comment by doomedraven** [comment] 2021-02-21 08:04
so did you solve your problem?

**Comment by g9990** [comment] 2021-02-21 12:48
> so did you solve your problem?

No not yet, still trying to figure out the problem

**Comment by doomedraven** [comment] 2021-02-21 13:07
So what you need to check
Hypervisor conf how did you set, then result server ip
Firewall both host and vm

Thats all

**Comment by g9990** [comment] 2021-02-23 12:32
The problem is solved, and everything is working fine. I have reinstalled the choco.bat file and reconfigured the iptables "as shown below". 

sudo iptables -t nat -A POSTROUTING -o tun0 -s 192.168.56.0/24 -j MASQUERADE
sudo iptables -P FORWARD DROP
sudo iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -s 192.168.56.0/24 -j ACCEPT
sudo iptables -A FORWARD -s 192.168.56.0/24 -d 192.168.56.0/24 -j ACCEPT
sudo iptables -A FORWARD -j LOG
echo 1 | sudo tee -a /proc/sys/net/ipv4/ip_forward
sudo sysctl -w net.ipv4.ip_forward=1

**Comment by doomedraven** [comment] 2021-02-23 12:34
that iptables not needed at all as it use rooter.py to handle that, but glad you fixed that. closing i will remove that iptables from docs as that is outdated part

**Closed by doomedraven** 2021-02-23 12:34 UTC

**Comment by kevoreilly** [comment] 2021-02-23 13:05
Great news - glad to hear the problem is now solved - as ever with the invaluable help of the man, the legend, doomedraven.

**Comment by doomedraven** [comment] 2021-02-23 13:06
lol i didn't do nothing at all :P @g9990 found it himself :)

**Comment by kevoreilly** [comment] 2021-02-23 13:07
It was just the confidence gained from knowing you were there :-D
