### ISSUE TITLE
Improper Condition Check in APIv2 VT Settings

### ISSUE THREAD

**Issue by Still34** [kevoreilly/CAPEv2#424] opened 2021-02-02 06:51 UTC
## Summary

At L569 of the newly implemented APIv2 views, the expected value is probably missing a `not` at the beginning, as this entire check always returns false even if the key is supplied. 

https://github.com/kevoreilly/CAPEv2/blob/ff34a5f0f7f358d60541e17c7269440e11abc89b/web/apiv2/views.py#L569

**Comment by Still34** [comment] 2021-02-02 06:55
Also, shouldn't the opt_apikey be optional if the VTDL_KEY is present in config?

**Comment by doomedraven** [comment] 2021-02-02 07:00
hello, good catch about `not`. about `VTDL_KEY` is used inside of the func, it just propagated in opt_apikey to function, but yes could be set directly

```
if settings.VTDL_KEY:
            details["headers"] = {'x-apikey': settings.VTDL_KEY}
elif details.get("apikey", False):
            details["headers"] = {'x-apikey': details["apikey"]}
```

**Comment by Still34** [comment] 2021-02-02 07:06
I'm still getting an error if the `not opt_apikey` is present though - even if I specify it in the request.

**Comment by doomedraven** [comment] 2021-02-02 07:08
on private or public?

**Comment by Still34** [comment] 2021-02-02 07:09
If you mean on a private instance or not, yes a private one.

**Comment by doomedraven** [comment] 2021-02-02 07:10
ok, then i will try to dig to it once i will have some time

**Comment by Still34** [comment] 2021-02-02 07:10
Everything works perfectly if I remove that specific check by the way, so it's something to do with that last check.

**Comment by doomedraven** [comment] 2021-02-02 19:09
i can't reproduce it, and it works for me just as it is, do you pass opt apikey or something?
is how my apiconf looks in auxiliar.conf
```
[virustotaldl]
# adds an option in the web interface to upload samples via VirusTotal
# downloads for a comma-separated list of MD5/SHA1/SHA256 hashes
enabled = yes
# note that unlike the VirusTotal processing module, the key required
# here is a Intelligence API key, not a Public API key
dlintelkey = APIKEY
dlpath = /tmp/
```

**Comment by Still34** [comment] 2021-02-03 03:10
I tried both passing and not passing the key, and yeah that's what my config looks like as well.

**Comment by doomedraven** [comment] 2021-02-03 06:44
can you pass error as without being able to reproduce it i can't do nothing and apiv2 not changed the code only framework that wraps the functions

**Comment by Still34** [comment] 2021-02-04 01:36
It just jumps straight into the line below the if condition, so the generic VT_KEY missing error.

**Comment by doomedraven** [comment] 2021-02-04 07:41
ok pushed change, this should fix, can you try it plz
```
if not (settings.VTDL_KEY or opt_apikey) or not settings.VTDL_PATH:
```

**Comment by doomedraven** [comment] 2021-02-06 09:53
closing this as i can't reproduce it, let me know if you still getiting issue

**Closed by doomedraven** 2021-02-06 09:53 UTC

**Comment by Still34** [comment] 2021-02-09 06:57
That appears to have fixed it. Thanks!

**Comment by doomedraven** [comment] 2021-02-09 07:14
Thanks for feedback
