### ISSUE TITLE
Analysis timeout

### ISSUE THREAD

**Issue by RyanInsolencee** [kevoreilly/CAPEv2#2019] opened 2024-03-20 09:06 UTC
## About accounts on [capesandbox.com](https://capesandbox.com/)
* Issues isn't the way to ask for account activation. Ping capesandbox in [Twitter](https://twitter.com/capesandbox) with your username

## This is open source and you are getting __free__ support so be friendly!

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [x ] I did read the README!
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x ] I have read and checked all configs (with all optional parts)

# Expected Behavior
to complete analysis

# Current Behavior
it will start the analysis as normal and after awhile it will timeout

## Steps to Reproduce

submitting URL for analysis 
web gui timeout setting is 500
will timeout without producing any reports and still shows running on gui when vm is already shutdown

## Context
ubuntu 22.04
vm running win10pro using kvm
let me know if you need any other information as im relatively new to this

## Failure Logs
`2024-03-20 16:58:28,624 [lib.cuckoo.core.scheduler] ERROR: Machine cuckoo1: the guest initialization hit the critical timeout, analysis aborted
Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 531, in launch_analysis
    guest.start_analysis(options)
  File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 245, in start_analysis
    self.wait_available()
  File "/opt/CAPEv2/lib/cuckoo/core/guest.py", line 154, in wait_available
    raise CuckooGuestCriticalTimeout(
lib.cuckoo.common.exceptions.CuckooGuestCriticalTimeout: Machine cuckoo1: the guest initialization hit the critical timeout, analysis aborted
2024-03-20 16:58:29,562 [lib.cuckoo.core.scheduler] ERROR:
Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 623, in run
    success = self.launch_analysis()
  File "/opt/CAPEv2/lib/cuckoo/core/scheduler.py", line 598, in launch_analysis
    raise CuckooDeadMachine()
lib.cuckoo.core.scheduler.CuckooDeadMachine
`

**Comment by RyanInsolencee** [comment] 2024-03-21 01:01
I do see the vm running from virt-manager and it does show that machine is found

**Comment by doomedraven** [comment] 2024-03-21 07:02
what about agent? did you test it that it response when vm is up?

**Comment by RyanInsolencee** [comment] 2024-03-21 09:50
also getting this error when i submit any files like html "PE type not recognised: 'DOS Header magic not found.'" is there anything that can be done about it?

**Comment by doomedraven** [comment] 2024-03-21 11:02
no, that is unrelated, is just your file is not a PE file. Well if snapshot is in running state, curl works, the uniq that i guess is wrong is the configuration. can you show your kvm.conf conf? and what is the ip of your vm? show me the output of curl plz

**Comment by RyanInsolencee** [comment] 2024-03-22 01:49
ip of vm is 192.168.122.137 

output of curl `{"message": "CAPE Agent!", "version": "0.17", "features": ["execpy", "execute", "pinning", "logs", "largefile", "unicodepath", "mutex"], "is_user_admin": true}f`

kvm.conf 
`[kvm]
# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = cuckoo1

interface = virbr0
# To connect to local or remote host
dsn = qemu:///system

[cuckoo1]
# Specify the label name of the current machine as specified in your
# libvirt configuration.
label = cuckoo1

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail. You may want to configure your network settings in
# /etc/libvirt/<hypervisor>/networks/
ip = 192.168.122.137

# Specify tags to display
# Tags may be used to specify on which guest machines a sample should be run
# NOTE - One of the following OS version tags MUST be included for Windows VMs:
# winxp,win7, win10, win11
# Some samples will only detonate on specific versions of Windows (see web.conf packages for more info)
# Example: MSIX - Windows >= 10
tags = win10,acrobat_reader11

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the KVM MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
snapshot = 21032024

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (virbr0 is the interface name):
# interface = virbr0

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
resultserver_ip = 10.100.2.176

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
resultserver_port = 2042

# Set the machine architecture
# Required to auto select proper machine architecture for sample
# x64 or x86
arch = x86

# (Optional) Specify whether or not the machine should be reserved, meaning that it will
# only be used for a detonation if specifically requested by its label.
# reserved = no

`

**Comment by doomedraven** [comment] 2024-03-22 06:17
ok the problem is easy here. 

1. you using NAT, be careful with that.
2. VM ip is 192.168.122.137
3. result server is 10.100.2.176


as you can see they are in different networks, why? fix that and it should works just fine

**Comment by RyanInsolencee** [comment] 2024-03-22 06:49
im using internet routing per the manual and as of a few hours ago the analysis started working properly after a reboot it does show me that task failed in the log but i do get the report generated with screenshots and different information

**Comment by doomedraven** [comment] 2024-03-22 06:53
well is up to you, with hostonly internet will work too. but is more secure, but that is out of scope of CAPE. glad that issue solved, if you will get the same error, put both thing in the same network range

**Closed by doomedraven** 2024-03-22 06:53 UTC
